# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "build"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/{img,js}/*"
    - "!src/assets/{img,js,less}/**/*"
  javascript:
    # Libraries requried by Foundation
    - "bower_components/jquery/dist/jquery.js"
    # Paths to your own project code are here
    - "src/assets/js/functions.js"
    - "src/assets/js/**/*.js"
