# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 8"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "build"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/{img,js}/*"
    - "!src/assets/{img,js,less}/**/*"
  javascript:
    # Libraries requried
    - "bower_components/bootstrap/dist/js/bootstrap.js"
    # Paths to your own project code are here
    - "src/assets/js/**/*.js"
